- website/src/components/Screens/BuySell.jsx
> remove main net (bitcoin)

- website/src/components/App.scss
- website/src/components/Bits/AmountSelect/styles.scss
- website/src/components/Bits/ToSelect.jsx
- website/src/components/Scrapbox/QuotePanel.jsx
- website/src/hooks/use1InchTokenList.jsx
- website/src/hooks/usePositions.jsx
- updated ToSelect component
- added "--color" theme variable
- updated AmountSelect component
- updated Swap/Trade page
> Thomas swap quote

- website/src/components/Bits/ToSelect.jsx
- website/src/components/Scrapbox/ApproveButton.jsx
- website/src/components/Scrapbox/DoItButton.jsx
- website/src/contexts/actionsContext.jsx
- website/src/data/TokenList.json
- website/src/hooks/usePositions.jsx
- added TokenList.json
- fixed an issue on "usePositions" hook
- added missing tokes for Polygon
> Thomas token list

- website/src/components/Bits/ToSelect.jsx
- website/src/data/TokenList.json
- fixed tokenlist issue
137 === "137" is false. but 137 == "137" is true.
- removed duplicated tokens
> fix tokenlist issue

- website/src/components/App.js
- website/src/components/App.scss
- website/src/components/Screens/BuySell.jsx
- website/src/hooks/usePositions.jsx
completed #96 ("USA Wallet needs to direct broke users to buy some crypto." task)
If no crypto is detected herd users into the "Buy/Sell" bridge to get some.
-Disable the Portfolio button.
-Disable the Swap/Trade button.
-Disable the Send/Receive button
If only Matic is detected in the user's portfolio then make swap/trade the default route.
> Thomas task 96

- website/package.json
- website/src/components/Blocks/TokenTable.jsx
- website/src/components/Blocks/TransactionList.jsx
- website/src/hooks/useTokenTransfers.jsx
- website/src/hooks/useTransactions.jsx
- Behaves MUUUCH better.  
- Kinda sketchy with the kind switch in the useEffect w/i TransactionList though.  
- The getERC20Transactions() data could be huge.  Might be a useMemo() for performance later.
- It'll do as a patch until somebody smarter in React than me thinks of a better way
.
> Fixed Tx history issues.

- website/package.json
- website/src/components/Bits/StartSend.jsx
- website/src/components/Blocks/TokenTable.jsx
- website/src/components/Blocks/TransactionList.jsx
- website/src/hooks/useTokenTransfers.jsx
- website/src/hooks/useTransactions.jsx
Reformulated with fresh Moralis parts!  Now the talky-talk as things happen!  Now more than EVER!  Ask for it by name! Get yours today!  And it works too!  (at least on my machine).
> Fix start send

- website/src/components/Scrapbox/DoItButton.jsx
- website/src/components/Scrapbox/MainStage.jsx
Swap Tx's are blocked by missing allowances? Especially on Matic/ETH/<native currency> #91
> completed #91

- website/src/components/Screens/BuySell.jsx
Tuned up API key and color selection.  Hoping it will just work on deployment.
> Tuning up Transak

- website/src/components/Screens/TopNavBar/index.jsx
- Hide Add Polygon Button if user is not Authenticated.
- #95
> Hide Polygon Button

- smartContract/.gitignore
- website/src/data/TokenList.json
new list can be found again in: /website/src/data/TokenList.json
> smart contracts 126 - small updates, new TokenList.json

- website/src/actions/_useUpdaters.js
- website/src/actions/useQuoteAction.js
- website/src/actions/useSwapAction.js
- website/src/actions/useTransferAction.js
- website/src/components/Bits/AmountSelect/index.jsx
- website/src/components/Bits/RequestQuote.jsx
- website/src/components/Bits/StartSend.jsx
- website/src/components/Bits/ToSelect.jsx
- website/src/components/Blocks/AddressPanel.js
- website/src/components/Blocks/SendPanel.jsx
- website/src/components/Blocks/SwapPanel.jsx
- website/src/components/Scrapbox/DoItButton.jsx
- website/src/components/Scrapbox/QuotePanel.jsx
- website/src/components/Screens/SendReceive.jsx
- website/src/contexts/actionsContext.jsx
- website/src/contexts/quoteContext.jsx
- website/src/data/TokenList.json
- add actions (hooks) and remove async/await from components
- update quoteContext
- update actionsContext
- fix tokenlist issue
> Thomas ruggedize architecture

- website/src/actions/useQuoteAction.js
- website/src/actions/useSwapAction.js
- website/src/actions/useTransferAction.js
- website/src/components/Bits/AuthButton/index.jsx
- website/src/components/Bits/StartSend.jsx
- website/src/components/Blocks/TransactionList.jsx
- website/src/contexts/actionsContext.jsx
- website/src/data/TokenList.json
- website/src/hooks/usePositions.jsx
"Fix Matic in swap #130" task
https://docs.moralis.io/moralis-server/sending-assets
> fixed transfer issue (#130)

- website/src/hooks/usePositions.jsx
Filter out "(Pos)" from all entries in portfolio names. #149
> filter out "(Pos)" from all entries in portfolio names

- website/src/components/App.js
- website/src/contexts/expertsContext.jsx
Title expert message should be cycled back to start upon logout. #150
> fix message issue

- website/src/actions/useSwapAction.js
- website/src/components/App.js
- website/src/components/Bits/FromSelect.jsx
- website/src/components/Bits/RequestQuote.jsx
- website/src/components/Bits/ToAddress/index.jsx
- website/src/components/Bits/ToSelect.jsx
- website/src/components/Blocks/TokenTable.jsx
- website/src/components/Scrapbox/DoItButton.jsx
- website/src/contexts/networkContext.jsx
- website/src/contexts/portfolioContext.jsx
- removed networkName, nativeSymbol on networkContext
- Clean up "bad code" wrapper issue in PortfolioContext #183
> Thomas work

- expo-mobileapp/index.js
- expo-mobileapp/package.json
- expo-mobileapp/src/components/Blocks/AddressPanel/index.tsx
- expo-mobileapp/src/components/Blocks/AddressPanel/styles.ts
- expo-mobileapp/src/components/Screens/SendReceive/index.tsx
- expo-mobileapp/src/navigation/DrawerNavigator.tsx
- expo-mobileapp/yarn.lock
- Linked #173
- Linked #175 
- Worked on Received Page, Added Copy Button,
- Integrated Moralis User Info with scanner and CopyButton
- Added Logout function and Icon for Logout Button
> Received Page and Logout Button function

- website/src/components/App.js
- website/src/components/App.scss
- website/src/components/Screens/Landing/Start/index.jsx
- website/src/components/Screens/Landing/Step1/index.jsx
- website/src/components/Screens/Landing/Step2/index.jsx
- website/src/components/Screens/Landing/Step3/index.jsx
- website/src/components/Screens/Landing/Step4/index.jsx
- website/src/components/Screens/Landing/Timeline/index.jsx
- website/src/components/Screens/Landing/Timeline/styles.scss
- website/src/components/Screens/Landing/index.jsx
Create a "milestones" display for complex user tasks. #22
> add landing page

- website/package.json
- website/yarn.lock
- Added Patched version of dependencies
- Linked #237 
`Note: Web3, Ansi-html don't have patched versions so we have to dismiss them manually.`
> 237-Added patched version for dependencies.

- website/src/components/Bits/AuthDrawer/index.jsx
- Added Fields under Form Component
- Added AutoComplete Attributes to hide warning for all inputs on Login Box
- Linked #242
> Login Drawer Input fields Fixes

- website/src/components/Screens/BuySell.jsx
Updated Transak api key variable name.
> update env variable

- website/src/components/App.scss
- website/src/components/Scrapbox/QuotePanel.jsx
- website/src/components/Screens/Home/TokenList.jsx
- website/src/components/Screens/Portfolio/TokenTable.jsx
Swap all token icon transparent backgrounds to white in both light and dark mode  #266
> update token icon background

- website/src/data/geckoCoinIds.json
Fix the Uniswap card icon #291
> fix uniswap token issue

- website/src/components/App.scss
- website/src/components/Screens/ExpertStage.jsx
- website/src/components/Screens/Home/TokenList.jsx
- website/src/components/Screens/Home/index.jsx
- website/src/components/Screens/Landing/index.jsx
Cinch up the home screen styling and layout. #294
> update home page

- website/src/components/Bits/AmountInput/index.jsx
- website/src/components/Blocks/SendPanel.jsx
- Linked #274 
- Fixed Feedbacks about Send Page.
> Fixed Feedbacks about Send/Receive Page.

- website/src/components/Bits/AmountInput/index.jsx
- website/src/components/Bits/AmountSelect/index.jsx
- website/src/components/Bits/FromSelect.jsx
- website/src/components/Bits/ToSelect.jsx
- website/src/components/Bits/TokenCard/index.jsx
- website/src/components/Screens/SendReceive.jsx
- website/src/contexts/actionsContext.jsx
Install trading buttons on the token info card #295
> update TokenCard, ToSelect and FromSelect

- website/src/components/App.js
- website/src/components/Screens/BuySell.jsx
- website/src/components/Screens/Home/TokenList.jsx
- website/src/components/Screens/NavBar.jsx
- website/src/components/Screens/TopNavBar/index.jsx
- website/src/hooks/usePolygonNetwork.jsx
- Linked #317 
- Changed Buy Crypto Text from Design 
- Linked #271 
- Checked all Text, Mostly Text is same, Only few items are different from Mobile Design. but I discussed those with Bob.
When you are reproducing/testing , we should follow this to delete user manually from server.
https://docs.moralis.io/moralis-server/users/crypto-login#manually-deleting-users
> Fixed Add Polygon Network issue for New Users.

- website/src/components/layouts/AuthLayout.jsx
- website/src/contexts/colorModeContext.jsx
Standardize log-in screen. #331
> fix input color

- website/src/components/layouts/AuthLayout.jsx
- website/src/containers/login/index.jsx
- website/src/containers/register/index.jsx
- website/src/containers/reset-password/index.jsx
Standardize log-in screen. #331
> update auth pages

- website/src/components/Blocks/AddressPanel.js
- website/src/containers/App.jsx
- website/src/containers/crypto-login/index.jsx
- Linked #347
- Linked #329 
- Added new Pages 
- Added checks if user don't have address, hide QRCode and show a message.
> Added New Pages + Receive Page Fixes

- website/src/components/Bits/ToSelect.jsx
- website/src/containers/App.jsx
> To Select issue Fixed.

- website/package.json
- website/src/components/Screens/Home/TokenList.jsx
- website/src/containers/App.jsx
- website/yarn.lock
Change the home page token to a horizontal carolsel of cards #345
> horizontal carolsel of cards

- website/src/components/Bits/RequestQuote.jsx
- website/src/components/Screens/TopNavBar/Logo.jsx
- Linked #359 
- Linked #348 
- Added Version Beta string in the bottom of Logo Text. 
- Fixed network.name Property is undefined
> Added Version Beta String and Fixed Name Property Undefined for Trade.

- website/src/components/App.js
- website/src/components/Bits/ToAddress/index.jsx
- website/src/components/Screens/Home/TokenList.jsx
- website/src/components/Screens/NavBar.jsx
- website/src/components/Screens/Portfolio/index.jsx
- website/src/contexts/networkContext.jsx
- website/src/contexts/portfolioContext.jsx
- website/src/hooks/usePolygonNetwork.jsx
- website/src/index.js
- website/yarn.lock
- Linked #346 
- Linked #321 
I tested new flow and following working for me , but you can test. 
- Linked #341
> Fixed Multiple Requests issue

- website/src/components/Screens/NavBar.jsx
- website/src/contexts/networkContext.jsx
- website/src/contexts/portfolioContext.jsx
- website/src/hooks/usePolygonNetwork.jsx
- Linked #366 
- Tested in different cases, its showing/hiding Token lists for my accounts. 
- Removed Extra Console Message to clean console.
> Disabled Trade Tab, If no Positions available.

- website/src/contexts/portfolioContext.jsx
- Linked #366 
- It was error of Position Mapping on Bob Side, I was not getting that because don't have enough tokens.
- Issue was fixed in Mapping using Optional Symbol
> Fixed issue of Position error of optional Image.

- website/src/components/UW/AlertDialog.jsx
- website/src/containers/reset-password/index.jsx
- Linked #372 
- Moved Code from Drawer to Page for Reset Password
- Added Alerts for Success and Failure.
> Reset Password Integrated

- website/src/contexts/portfolioContext.jsx
Fix renBTC in portfolio display #377
> fix portfolio issue

- website/src/containers/App.jsx
- website/src/containers/onboarding/index.jsx
- website/src/contexts/networkContext.jsx
- website/src/index.js
Redirect all missing MetaMask and/or Polygon network issues to Marketing onboarding page bug #385
> update routing and onboarding page

- website/src/components/App.js
- website/src/components/Bits/OnBoardingButton.jsx
- website/src/containers/App.jsx
- website/src/containers/NoSafari/index.jsx
- website/src/containers/onboarding/index.jsx
Shunts Safari:
Also updates onboarding routes:
Closes 391
> Detect safari

- website/package.json
- website/src/components/App.js
- website/src/components/Screens/OnRamper.jsx
- website/yarn.lock
> OnRamper installed and functioning.

- website/src/components/Screens/ExpertStage.jsx
- website/src/components/Screens/Portfolio/index.jsx
- website/src/containers/NoSafari/index.jsx
Total value now displayed in expert stage.
Expert stage now has a "Call for help." button floater.
Closes #400 #401
> Call for help done.  Brave removed.

- website/src/components/App.js
- website/src/components/Bits/InstallMetaMaskButton.jsx
- website/src/components/Screens/Portfolio/index.jsx
- website/src/components/Screens/TopNavBar/index.jsx
- website/src/containers/App.jsx
- website/src/containers/QuotePanel/index.jsx
- website/src/containers/onboarding/index.jsx
- website/src/hooks/usePolygonNetwork.jsx
Fixed buggy log-in by removing most checks.
> Fix route onboarding

- website/src/components/Bits/TradeTokens.jsx
- website/src/containers/QuotePanel/index.jsx
Added checks for MetaMask and Polygon to trade button container.
> Installed onboarding pre-trade.  Marked Ivan's trade component.

- website/src/components/App.js
- website/src/components/Screens/Transak.jsx
- website/src/containers/App.jsx
Swapped OnRamper widget out.
Swapped Transak widget in.
Switched default Transak crypto from mUSDC to MATIC.
(Updated Transak API key on Netlify).
Switched default screen from register to log-in.
> Restored Transak

- website/src/components/Screens/Transak.jsx
Fixed NODE_ENV issue in Transak component.
> NODE_ENV fix.

- website/src/components/Screens/Transak.jsx
Don't know why this works on local.  Mysteries of the Transak widget component.
> Force touch user address.

- website/src/components/Bits/AuthButton/index.jsx
Adding a backpath to reconnect if logging on doesn't.  Attempting to overcome problem on Netlify server with login vs. recovering user address from Moralis.
> Add reconnect into logout button.

- website/src/components/Bits/ConnectWallet/index.jsx
- website/src/contexts/portfolioContext.jsx
Adding debug for when portfolio fetch is fired.
> Portfolio debugging.

- website/src/components/Bits/TradeTokensWithIvan/index.jsx
"transactions are underfunded".  Should fix it.
> Doubling down the Matic fees
